pub mod ai_errors;
pub mod cloud_api;
pub mod compatibility;
pub mod context;
pub mod context_summarizer;
pub mod hardware_probe;
pub mod inference;
pub mod jobs;
pub mod model_loader;
pub mod model_metadata;
pub mod model_registry;
pub mod offline_mode;
pub mod permissions;
pub mod project_index;
pub mod prompt_builder;
pub mod runtime;
pub mod tool_router;

pub use ai_errors::{AiError, AiResult};
pub use compatibility::{AiCompatibilityReport, DeviceTier, RecommendedModel};
pub use context::{AiContext, AiContextRequest};
pub use hardware_probe::HardwareProfile;
pub use inference::{AiGenerationResult, AiPrompt, GenerateOptions};
pub use jobs::{AiJob, AiJobId, AiJobStatus};
pub use model_metadata::{ForgeModelMetadata, ModelFormat, ModelStatus};
pub use model_registry::{InstalledModel, ModelRegistry};
pub use permissions::{AiPermissionSet, PermissionMode};
pub use runtime::{LocalAiRuntime, RuntimeModelHandle};
pub use tool_router::{AiProposedAction, AiToolDescriptor, AiToolRouter};
